"""changed location id

Revision ID: 0f1c58b00feb
Revises: 4c03d17cc0d2
Create Date: 2025-04-19 12:44:39.035873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1c58b00feb'
down_revision: Union[str, None] = '4c03d17cc0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link', sa.String(length=128), nullable=False))
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'telegram_link')
    # ### end Alembic commands ###
