"""changed location id

Revision ID: 4c03d17cc0d2
Revises: eabcc1f91a85
Create Date: 2025-04-19 12:30:41.357551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c03d17cc0d2'
down_revision: Union[str, None] = 'eabcc1f91a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
