"""remove profile pic

Revision ID: 7c553bbf1039
Revises: 0f1c58b00feb
Create Date: 2025-04-21 14:30:30.353272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c553bbf1039'
down_revision: Union[str, None] = '0f1c58b00feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
