"""remove profile pic

Revision ID: 9adc3f677205
Revises: f4f4f732db5d
Create Date: 2025-04-23 13:30:06.085921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9adc3f677205'
down_revision: Union[str, None] = 'f4f4f732db5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locations',
    sa.Column('Location_id', sa.Integer(), nullable=False),
    sa.Column('Country', sa.String(length=128), nullable=False),
    sa.Column('City', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('Location_id')
    )
    op.create_table('Users',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('TelegramLink', sa.String(length=128), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=False),
    sa.Column('Location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Location_id'], ['Locations.Location_id'], ),
    sa.PrimaryKeyConstraint('User_id')
    )
    op.create_table('Interests',
    sa.Column('Interest_id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=False),
    sa.Column('Description', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['Users.User_id'], ),
    sa.PrimaryKeyConstraint('Interest_id')
    )
    op.create_table('User_likes',
    sa.Column('Liker_id', sa.Integer(), nullable=False),
    sa.Column('Liked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Liked_id'], ['Users.User_id'], ),
    sa.ForeignKeyConstraint(['Liker_id'], ['Users.User_id'], ),
    sa.PrimaryKeyConstraint('Liker_id', 'Liked_id')
    )
    op.drop_table('interests')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('user_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('liker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liked_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['users.user_id'], name='user_likes_liked_id_fkey'),
    sa.ForeignKeyConstraint(['liker_id'], ['users.user_id'], name='user_likes_liker_id_fkey'),
    sa.PrimaryKeyConstraint('liker_id', 'liked_id', name='user_likes_pkey')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.INTEGER(), server_default=sa.text("nextval('locations_location_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('location_id', name='locations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('telegram_link', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name='users_location_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('interests',
    sa.Column('interest_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='interests_user_id_fkey'),
    sa.PrimaryKeyConstraint('interest_id', name='interests_pkey')
    )
    op.drop_table('User_likes')
    op.drop_table('Interests')
    op.drop_table('Users')
    op.drop_table('Locations')
    # ### end Alembic commands ###
