"""normal sql

Revision ID: eabcc1f91a85
Revises: d1f74d4d22c6
Create Date: 2025-04-18 20:44:07.630112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabcc1f91a85'
down_revision: Union[str, None] = 'd1f74d4d22c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_likes',
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('liker_id', 'liked_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_likes')
    # ### end Alembic commands ###
